spring:
  application:
    name: user
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/user
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${SERVER_HTTP_PORT:8080}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

lib:
  security:
    anonymous-requests:
      - method: POST
        pattern: "/web/api/tokens"
      - method: POST
        pattern: "/web/api/users"